---
title: Bevestig een LED aan een weerstand met behulp van isolatietape
hero_image: images/banner.png
description: Hoe bevestig ik een LED aan een weerstand met behulp van isolatietape.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - title: Bevestig een LED aan een weerstand met behulp van isolatietape
