title: Attach an LED to a resistor using electrical tape
hero_image: images/banner.png
description: How to attach an LED to a resistor using electrical tape.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - title: Attach an LED to a resistor using electrical tape
