title: Attach an LED to a resistor using electrical tape
hero_image: images/banner.png
description: led-resistor-electrical-tape description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
