---
title: ربط مصباح LED مع مقاومة بإستعمال شريط كهربائي
hero_image: images/banner.png
description: كيفية ربط مصياح LED مع مقاومة بإستعمال شريط كهربائي.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - 
    title: ربط مصباح LED مع مقاومة بإستعمال شريط كهربائي
