---
title: Fäst en lysdiod till ett motstånd med hjälp av eltejp
hero_image: images/banner.png
description: Hur man fäster en lysdiod till ett motstånd med hjälp av eltejp.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - title: Fäst en lysdiod till ett motstånd med hjälp av eltejp
