---
title: Attacher une LED à une résistance électrique à l'aide d'un ruban isolant
hero_image: images/banner.png
description: Comment attacher une LED à une résistance électrique en utilisant du ruban isolant.
version: 4
listed: false
copyedit: false
last_tested: "2022-01-25"
steps:
  - 
    title: Attacher une LED à la résistance électrique à l'aide d'un ruban isolant
